version: '3.8'
services:
  redis:
    container_name: redis
    image: redislabs/redistimeseries
    ports:
      - 6379:6379
  aws:
    container_name: aws
    image: localstack/localstack:latest
    environment:
      DEBUG: 1
      AWS_DEFAULT_REGION: us-east-1
      LAMBDA_EXECUTOR: local
      # Docker network that lambdas are reachable by.
      # This makes it easier for Lambads to be invoked by other
      # external Docker containers.
      LAMBDA_DOCKER_NETWORK: local_network
      # Use our local files via Docker volumes to define our Lambdas
      LAMBDA_REMOTE_DOCKER: 0
      # Spin up the Lambda module
      SERVICES: lambda,dynamodb
    ports:
      - 4566-4583:4566-4583
    volumes:
      # Let LocalStack create new docker containers by giving
      # LocalStack access to your computer's Docker daemon
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.cache/localstack/volume:/var/lib/localstack
