version: '3.8'
services:
  codeless_backend:
    image: apisentinel/codeless-backend:latest
    container_name: codeless_backend
    environment:
      - spring_redis_host=redis
      - spring_redis_port=6379
      - spring_mail_password=
    ports:
      - 8080:8080
    depends_on:
      - redis

  redis:
    image: redislabs/redistimeseries
    container_name: redis
    ports:
      - 6379:6379