version: '3.1'

services:
  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql