version: '3.1'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql